In [25]:
import pandas as pd,numpy as np

**Probability Ratio Encoding**
1. Probability of Survived based on Cabin -- Categorical Features
2. if i know the probability of Survived then i can find the probability of not Survived -- not Survived(1-Survived)
3. finding the probability ratio by  dividing survived  with not survived columns
4. Making the dictionary to map cabin with probability ratio
5. Replace with Categorical Feature

In [3]:
#reading the dataset
df=pd.read_csv('/content/train.csv',usecols=['Cabin','Survived'])
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [5]:
#filling the nan values with "Missing"
df["Cabin"].fillna("Missing",inplace=True)
df.head()

   Survived    Cabin
0         0  Missing
1         1      C85
2         1  Missing
3         1     C123
4         0  Missing

In [8]:
#taking only the cabin number
df["Cabin"]=df["Cabin"].astype(str).str[0]
df.head()

   Survived Cabin
0         0     M
1         1     C
2         1     M
3         1     C
4         0     M

In [10]:
#finding the probability of survived columns with respect to cabin number
prob_df=df.groupby(["Cabin"])["Survived"].mean()

In [12]:
#making the dataframe of prob_df
prob_df = pd.DataFrame(prob_df)
prob_df

       Survived
Cabin
A      0.466667
B      0.744681
C      0.593220
D      0.757576
E      0.750000
F      0.615385
G      0.500000
M      0.299854
T      0.000000

In [13]:
#adding the columns dead by subtracting 1 with survived mean 
prob_df["Died"] = 1-prob_df["Survived"]

In [28]:
prob_df.head(10)

       Survived      Died  Probability_ratio
Cabin
A      0.466667  0.533333           0.875000
B      0.744681  0.255319           2.916667
C      0.593220  0.406780           1.458333
D      0.757576  0.242424           3.125000
E      0.750000  0.250000           3.000000
F      0.615385  0.384615           1.600000
G      0.500000  0.500000           1.000000
M      0.299854  0.700146           0.428274
T      0.000000  1.000000           0.000000

In [17]:
#probability ratio
prob_df["Survived"]/prob_df["Died"]

Cabin
A    0.875000
B    2.916667
C    1.458333
D    3.125000
E    3.000000
F    1.600000
G    1.000000
M    0.428274
T    0.000000
dtype: float64

In [18]:
#making probability ratio by  dividing survived columns with died columns 
prob_df["Probability_ratio"] = prob_df["Survived"]/prob_df["Died"]

In [27]:
prob_df.head(10)

       Survived      Died  Probability_ratio
Cabin
A      0.466667  0.533333           0.875000
B      0.744681  0.255319           2.916667
C      0.593220  0.406780           1.458333
D      0.757576  0.242424           3.125000
E      0.750000  0.250000           3.000000
F      0.615385  0.384615           1.600000
G      0.500000  0.500000           1.000000
M      0.299854  0.700146           0.428274
T      0.000000  1.000000           0.000000

In [22]:
#making the dictionary to map with Cabin columns
prob_encoded=prob_df["Probability_ratio"].to_dict()

In [23]:
df["Cabin_encoded"]= df["Cabin"].map(prob_encoded)

In [26]:
df.head(10)

   Survived Cabin  Cabin_encoded
0         0     M       0.428274
1         1     C       1.458333
2         1     M       0.428274
3         1     C       1.458333
4         0     M       0.428274
5         0     M       0.428274
6         0     E       3.000000
7         0     M       0.428274
8         1     M       0.428274
9         1     M       0.428274